import json
from .core import get_db_connection

DOCUMENT_DISCLAIMER="""\
**This document is Generated by Artificial Intelligence (AI). Accuracy is not \
 guaranteed.**\n\n
"""

def get_further_reading_section(start_time, end_time) -> list:
    db_con = get_db_connection()
    db_cur = db_con.cursor()
    db_cur.execute(""" 
        SELECT s.json 
        FROM article_summaries s
        JOIN articles a ON (s.article_id = a.id)
        WHERE a.fetched_at BETWEEN :start_time AND :end_time;
    """, {
        "start_time": start_time,
        "end_time": end_time
    })
    article_summary_rs = db_cur.fetchall()

    further_reading = "\n\n# Further Reading\n"
    for article_summary in article_summary_rs:
        summary_json = json.loads(article_summary[0])

        further_reading += f"## [{summary_json['title']}]({summary_json['url']})\n"
        further_reading += f"*Severity*: {summary_json['severity']}\n\n"
        further_reading += summary_json['summary'] + "\n\n"
        if len(summary_json['ioc_list']):
            further_reading += "\n\n|IOC Value|Type|Confidence\n|---|---|---|\n"
            for ioc in summary_json['ioc_list']:
                further_reading += f"|{ioc['value']}|{ioc['type']}|{ioc['confidence']}|\n"

        if len(summary_json['vulnerability_list']):
            further_reading += "\n\n|Vulnerability|Software|\n|---|---|\n"
            for vuln in summary_json['vulnerability_list']:
                further_reading += f"|{vuln['cve_id']}|{vuln['software_name']}|\n"
 
    return (further_reading)